import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Card from '@/componentes/card'
import Clock from '@/componentes/Clock'
import data from '@/data/data.json'
import Profile from '@/componentes/user/profile'

import Reloj from '@/componentes/Reloj'

const inter = Inter({ subsets: ['latin'] })

// Reemplazar esta constante con la info de data.json...
const myData = []//data
const urlRequest = []//myData[0].url

export default function Home() {
  /* Esto es una promesa de obtener datos desde algun backend*/
  /*fetch(urlRequest)
    .then(response => console.log("Se cumplio la promesa: " + response))
    .catch(reason => console.log("NO cumplio la promesa: " + reason))
*/
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Profile></Profile>
        <Reloj />
        
        {
          myData.map(element => (
            <Card img={element.image} name={element.name} ></Card>
          ))
        }
      </main>
    </>
  )
}
