import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Footer from '@/componentes/footer/footer'
import Navbar from '@/componentes/navbar/navbar'
import DarkModef from '@/componentes/buttons/dark_mode_f'
import MainContextProvider from '@/context/maincontextprovider'
import Message from '@/componentes/message/message'

const inter = Inter({ subsets: ['latin'] })

export default function SaveState() {
  
   
    return (
      <>
        <Head>
          <title>Component Test</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <MainContextProvider>
          <DarkModef></DarkModef>
          <main className={styles.main}>
            <Message text="Prueba de save state"></Message>
          </main>
        </MainContextProvider>
      </>
    )
  }
  