import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import ButtonPlus from '@/componentes/buttons/button_plus'
import ButtonPlusF from '@/componentes/buttons/button_plusf'
import Footer from '@/componentes/footer/footer'
import Navbar from '@/componentes/navbar/navbar'
import DarkModef from '@/componentes/buttons/dark_mode_f'
import InitialLogin from '@/componentes/login/initialLogin'
import MainContextProvider from '@/context/maincontextprovider'
import Message from '@/componentes/message/message'

const inter = Inter({ subsets: ['latin'] })

export default function Test() {
  
   
    return (
      <>
        <Head>
          <title>Component Test</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <MainContextProvider>
          <Navbar></Navbar>
          <DarkModef></DarkModef>
          <br></br>
          <InitialLogin/>
          <main className={styles.main}>
            <ButtonPlus></ButtonPlus>
            <Message text="Hello"></Message>
            <ButtonPlusF></ButtonPlusF>
          </main>
          <Footer></Footer>
        </MainContextProvider>
      </>
    )
  }
  