import Head from 'next/head'

import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import ButtonPlus from '@/componentes/buttons/button_plus'
import Footer from '@/componentes/footer/footer'
import Navbar from '@/componentes/navbar/navbar'
import DarkModef from '@/componentes/buttons/dark_mode_f'
import InitialLogin from '@/componentes/login/initialLogin'
import { mainContextProvider } from '@/context/maincontextprovider'
import { useContext } from 'react'
import { maincontextState } from '@/context/maincontextprovider'

const inter = Inter({ subsets: ['latin'] })

export default function Test() {
  
    let context = useContext(maincontextState);
    let darkMode = context.darkMode;
    let isLoggedIn = context.isLoggedIn;

    return (
      <>
        <Head>
          <title>Component Test</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <mainContextProvider>
          <Navbar></Navbar>
          <DarkModef></DarkModef>

          <InitialLogin/>
          <main className={styles.main}>
            <ButtonPlus></ButtonPlus>
            <span className={darkMode?styles.dark:styles.light}>TEMP</span>
          </main>
          <Footer></Footer>
        </mainContextProvider>
      </>
    )
  }
  