import Head from 'next/head'

import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import ButtonPlus from '@/componentes/buttons/button_plus'
import Footer from '@/componentes/footer/footer'
import Navbar from '@/componentes/navbar/navbar'
import Darkmode from '@/componentes/buttons/darkmode'
import { useContext } from 'react'
import { mainContext } from '@/context/maincontext'

const inter = Inter({ subsets: ['latin'] })

export default function Test() {

    let { darkMode } = useContext(mainContext);

    return (
      <>
        <Head>
          <title>Component Test</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Navbar></Navbar>
        <Darkmode></Darkmode>
        <main className={styles.main}>
          <ButtonPlus></ButtonPlus>
          <span className={darkMode?styles.dark:styles.light}>TEMP</span>
        </main>
        <Footer></Footer>
      </>
    )
  }
  