import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import MainContextProvider from '@/context/maincontextprovider'
import { WebChatContainer } from '@ibm-watson/assistant-web-chat-react';
import { config } from '../config/config';

const inter = Inter({ subsets: ['latin'] })

export default function WatsonChat() {
  
   
    return (
      <>
        <Head>
          <title>Component Test</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <MainContextProvider>
          <main className={styles.main}>
            Hello Watson!
          <WebChatContainer config={config} />
          </main>
        </MainContextProvider>
      </>
    )
  }